### ISSUE TITLE
no longer able to update the schema

### ISSUE THREAD

**Issue by willgart** [Bertverbeek4PS/bc2adls#139]
Hi,

Today I'm receiving this error when I try to add table to my export config:

If requesting support, please provide the following details to help troubleshooting:

Error message: 
Could not create blob https://onelake.dfs.fabric.microsoft.com/<workspace>/<BC lakehouse>.Lakehouse/Files/GLAccount-15.cdm.json. {"error":{"code":"ArtifactNotFound","message":"Request Failed with Artifact '<BC lakehouse>.Lakehouse' is not found in workspace '<workspace>'."}}

Internal session ID: 

Application Insights session ID: 

Client activity id: 

Time stamp on error: 
2024-05-23T10:51:36.6300832Z

User telemetry id: 

AL call stack: 
"ADLSE Gen 2 Util"(CodeUnit 82568).CreateBlockBlob line 35 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Gen 2 Util"(CodeUnit 82568).CreateOrUpdateJsonBlob line 5 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Communication"(CodeUnit 82562).UpdateCdmJsons line 13 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Execute"(CodeUnit 82561).ExportSchema line 34 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Execution"(CodeUnit 82569).SchemaExport line 28 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Setup"(Page 82560)."SchemaExport - OnAction"(Trigger) line 4 - Azure Data Lake Storage Export by The bc2adls team

everything worked fine until today.
I just wanted to add new table in the export config.
but this is not working.

I tried to use GUIDs instead of lakehouse and workspace names, but the GUID are not recognized at all by the code. (maybe adding a flag like "lakehouse is guid" could help for that, as using a guid doesn't required adding .Lakehouse to the URL)
for sure I double check the security, and nothing changed and the data were exported until I stop the export to add new tables.

**Comment by Bertverbeek4PS** [comment]
Hi @willgart I think it is the same issue as:
https://github.com/Bertverbeek4PS/bc2adls/issues/132

Workspace can only by lowercase and uppercase and numbers with no spaces etc.

I have updated it also that you can use GUIDS in the latest version.
(but in the latest version you can only use lowercase, numbers and underscrore or a GUID.

**Comment by willgart** [comment]
I'll try renaming my workspace. I have a space on it.
but this worked before

yep, this works when I replace my spaces with _ 

GUID is not working for me. the systeme is not able to find the workspace + lakehouse at all. it still try to add .lakehouse at the end while a guid access did not require it.

**Comment by Bertverbeek4PS** [comment]
> I'll try renaming my workspace. I have a space on it. but this worked before
> 
> yep, this works when I replace my spaces with _
> 
> GUID is not working for me. the systeme is not able to find the workspace + lakehouse at all. it still try to add .lakehouse at the end while a guid access did not require it.

Fabric have changed something in the API so with spaces it isn't working anymore.
In the newest release that I created today GUID are now also working. Before it wasn't indeed working.

**Comment by Bertverbeek4PS** [comment]
Well thanks to @greglong1 and @lhammerbh who did all the checks 😄

**Comment by GC-Martin** [comment]
Hi, unfortunately I encounter this problem even though I downloaded the latest release (if I'm doing it correctly; I downloaded the asset from 24.25 release: https://github.com/Bertverbeek4PS/bc2adls/releases

When I enter the GUID then I already get an error on exporting schema:

{"error":{"code":"BadRequest","message":"WorkspaceId and ArtifactId should be either valid Guids or valid Names"}}

When I enter the Workspace name (which I altered to not contain spaces) then the export schema returns no errors but then the export does:

Invalid format of GUID string.

Not sure if I'm really on the fixed version, as it states 24.24 as version number instead of 24.25.

**Comment by LumosPatronum** [comment]
@GC-Martin when i switched the lakehouse to also be the GUID instead, that's what solved the issue for me. so i use the GUID on both the workspace and lakehouse. 

this is all new to me so i wasnt really sure which to download when it comes to the latest release as well but i just download it straight form the main repository page as a zip, instead from the assets on the release page. 
does it make a difference where its downloaded from? When i built the source code that was downloaded from the zip file, the ".app" that got built had the exact same version as downloading [bc2adls-release_24.23-Apps-24.24.101.0.zip](https://github.com/Bertverbeek4PS/bc2adls/releases/download/24.25.0/bc2adls-release_24.23-Apps-24.24.101.0.zip)

**Comment by GC-Martin** [comment]
@LumosPatronum thank you! That did the trick. I used GUID on both now.

Regarding which to download; I am also not sure. I assume a 'release' is more stable than current state of the main branch, but for me this is also new. I don't usually work with github repo's nor did I ever create a BC extension. It would be nice if less knowledge was assumed and someone could add some installation instructions to the Readme.

**Comment by LumosPatronum** [comment]
@GC-Martin thanks for confirming that worked, I had reported the same issue on #147 and Bert had said that he will look into it when he gets a chance. I was confused too since my lakehouse and workspace were all lowercase but yet it wouldnt work until i switched them both to be GUID.
@Bertverbeek4PS  would really appreciate it if you could let us know what downloading the latest release entails? do we have to download the source-file.zip and build it on vscode or can we just download the .app file within [bc2adls-release_24.23-Apps-24.24.101.0.zip](https://github.com/Bertverbeek4PS/bc2adls/releases/download/24.25.0/bc2adls-release_24.23-Apps-24.24.101.0.zip) under each release. just wanted to make sure that i am downloading the correct version! :)

**Comment by Bertverbeek4PS** [comment]
Hi @GC-Martin and @LumosPatronum.
You must enter in Lakehouse and workspace both a valid GUID of both valid name (without any space).
Like shit:
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_

If you want to download only the app without you need to compile you can look in the releases for BC23 and BC24.
Like this:
https://github.com/Bertverbeek4PS/bc2adls/releases/download/24.25.0/bc2adls-release_24.23-Apps-24.24.101.0.zip
